name: Run CI checks

on:
    pull_request:
        types: [opened, synchronize, labeled, unlabeled, reopened]
jobs:
    check-labels:
        name: Check labels
        runs-on: ubuntu-latest
        steps:
            - uses: docker://agilepathway/pull-request-label-checker:latest
              with:
                  one_of: major,minor,patch
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
    ci-checks:
        needs: check-labels
        runs-on: ubuntu-latest

        strategy:
            matrix:
                mongodb-version: ["5.0.9"]

        steps:
            - name: Start MongoDB
              uses: MongoCamp/mongodb-github-action@1.2.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}
            - run: curl http://localhost:27017

            - uses: actions/checkout@v5
            - name: Install UV
              uses: astral-sh/setup-uv@v7.1.1
            - name: Set up Python
              run: uv python install
            - name: Install the project
              run: uv sync --locked --all-extras --dev
            - name: Test
              run: uv run poe tests
            - name: Lint
              run: uv run poe lint
            - name: Upload coverage report to Codecov
              uses: codecov/codecov-action@v5.5.1
              with:
                  verbose: true
                  token: ${{ secrets.CODECOV_TOKEN }}
